#!/bin/sh /etc/rc.common
START=90

start()
{
    /bin/ash -c "echo DEBUG start"
    # /bin/ash -c "minieap -b3"
}

stop()
{
    /bin/ash -c "echo DEBUG stop"
    # minieap -k
}

restart()
{
    /bin/ash -c "echo DEBUG restart"
    # minieap -k 1
}
